version: '3.8'

services:
  db:
    image: postgres:13
    container_name: db
    environment:
      - POSTGRES_USER=app_user
      - POSTGRES_PASSWORD=secure_password
      - POSTGRES_DB=app_user
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./backend/initdb:/docker-entrypoint-initdb.d
    ports:
      - "5432:5432"
    networks:
      - app-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U app_user -d app_user"]
      interval: 10s
      timeout: 5s
      retries: 5

  backend:
    build: ./backend
    container_name: backend
    environment:
      - DATABASE_URL=postgresql://app_user:secure_password@db:5432/app_user
    depends_on:
      - db
    networks:
      - app-network

  migrate:
    build: ./backend
    container_name: migrate
    command: >
      bash -c "
        until pg_isready -h db -p 5432 -U app_user; do
          echo 'Waiting for PostgreSQL...';
          sleep 1;
        done;
        alembic upgrade head;
      "
    environment:
      - DATABASE_URL=postgresql://app_user:secure_password@db:5432/app_user
    depends_on:
      - db
    networks:
      - app-network
    restart: on-failure

  frontend:
    build: ./frontend
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/app
      - /app/node_modules
      - /app/.next
    environment:
      - NEXT_PUBLIC_API_URL=http://backend:8000/api/v1
    depends_on:
      - backend
    networks:
      - app-network

  nginx:
    build: ./nginx
    container_name: nginx
    ports:
      - "80:80"
    depends_on:
      - frontend
      - backend
    networks:
      - app-network

volumes:
  postgres_data:

networks:
  app-network:
