version: '3.8'

services:
  frontend:
    build:
      context: ./frontend
    container_name: frontend
    environment:
      - PUBLIC_URL=/
    depends_on:
      - backend
    networks:
      - app-network

  backend:
    build:
      context: ./backend
    container_name: backend
    environment:
      - DATABASE_URL=postgresql://user:password@db:5432/your_db
    depends_on:
      - db
    networks:
      - app-network

  db:
    image: postgres:13
    container_name: db
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: your_db
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - app-network

  nginx:
    build:
      context: ./nginx
    container_name: nginx
    ports:
      - "80:80"
    depends_on:
      - frontend
      - backend
    networks:
      - app-network

  migrate:
    build:
      context: ./backend
    container_name: migrate
    command: alembic upgrade head
    depends_on:
      - db
    environment:
      - DATABASE_URL=postgresql://user:password@db:5432/your_db
    networks:
      - app-network

volumes:
  postgres_data:

networks:
  app-network:
