"""Initial migration

Revision ID: 12692f14f75a
Revises: 
Create Date: 2024-11-07 00:41:09.519550

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '12692f14f75a'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_categories_name', table_name='categories')
    op.drop_index('idx_categories_parent_id', table_name='categories')
    op.drop_constraint('uq_category_name_parent', 'categories', type_='unique')
    op.create_index(op.f('ix_categories_category_id'), 'categories', ['category_id'], unique=False)
    op.drop_constraint('fk_parent_category', 'categories', type_='foreignkey')
    op.create_foreign_key(None, 'categories', 'categories', ['parent_id'], ['category_id'], ondelete='SET NULL')
    op.drop_index('idx_product_matching_log_confidence_score', table_name='productmatchinglog')
    op.drop_index('idx_product_matching_log_product_id', table_name='productmatchinglog')
    op.create_index(op.f('ix_productmatchinglog_log_id'), 'productmatchinglog', ['log_id'], unique=False)
    op.drop_index('idx_pricehistory_product_store_id', table_name='productpricehistory')
    op.drop_index('idx_pricehistory_recorded_at', table_name='productpricehistory')
    op.create_index(op.f('ix_productpricehistory_price_history_id'), 'productpricehistory', ['price_history_id'], unique=False)
    op.drop_index('idx_products_category_id', table_name='products')
    op.drop_index('idx_products_name', table_name='products')
    op.drop_index('idx_products_name_trgm', table_name='products')
    op.create_index(op.f('ix_products_name'), 'products', ['name'], unique=False)
    op.create_index(op.f('ix_products_product_id'), 'products', ['product_id'], unique=False)
    op.drop_constraint('fk_category', 'products', type_='foreignkey')
    op.create_foreign_key(None, 'products', 'categories', ['category_id'], ['category_id'], ondelete='SET NULL')
    op.drop_index('idx_productstoredata_additional_attributes', table_name='productstoredata')
    op.drop_index('idx_productstoredata_last_updated', table_name='productstoredata')
    op.drop_index('idx_productstoredata_matching_status', table_name='productstoredata')
    op.drop_index('idx_productstoredata_price_per_unit', table_name='productstoredata')
    op.drop_index('idx_productstoredata_product_id', table_name='productstoredata')
    op.drop_index('idx_productstoredata_product_price', table_name='productstoredata')
    op.drop_index('idx_productstoredata_store_description_trgm', table_name='productstoredata')
    op.drop_index('idx_productstoredata_store_id', table_name='productstoredata')
    op.drop_index('idx_productstoredata_store_product_name_trgm', table_name='productstoredata')
    op.create_index(op.f('ix_productstoredata_product_store_id'), 'productstoredata', ['product_store_id'], unique=False)
    op.drop_constraint('fk_product', 'productstoredata', type_='foreignkey')
    op.drop_constraint('fk_store', 'productstoredata', type_='foreignkey')
    op.create_foreign_key(None, 'productstoredata', 'products', ['product_id'], ['product_id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'productstoredata', 'stores', ['store_id'], ['store_id'], ondelete='CASCADE')
    op.drop_index('idx_stores_name', table_name='stores')
    op.create_index(op.f('ix_stores_store_id'), 'stores', ['store_id'], unique=False)
    op.create_index(op.f('ix_units_unit_id'), 'units', ['unit_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_units_unit_id'), table_name='units')
    op.drop_index(op.f('ix_stores_store_id'), table_name='stores')
    op.create_index('idx_stores_name', 'stores', ['name'], unique=False)
    op.drop_constraint(None, 'productstoredata', type_='foreignkey')
    op.drop_constraint(None, 'productstoredata', type_='foreignkey')
    op.create_foreign_key('fk_store', 'productstoredata', 'stores', ['store_id'], ['store_id'], onupdate='CASCADE', ondelete='CASCADE')
    op.create_foreign_key('fk_product', 'productstoredata', 'products', ['product_id'], ['product_id'], onupdate='CASCADE', ondelete='CASCADE')
    op.drop_index(op.f('ix_productstoredata_product_store_id'), table_name='productstoredata')
    op.create_index('idx_productstoredata_store_product_name_trgm', 'productstoredata', ['store_product_name'], unique=False)
    op.create_index('idx_productstoredata_store_id', 'productstoredata', ['store_id'], unique=False)
    op.create_index('idx_productstoredata_store_description_trgm', 'productstoredata', ['store_description'], unique=False)
    op.create_index('idx_productstoredata_product_price', 'productstoredata', ['product_id', 'price'], unique=False)
    op.create_index('idx_productstoredata_product_id', 'productstoredata', ['product_id'], unique=False)
    op.create_index('idx_productstoredata_price_per_unit', 'productstoredata', ['price_per_unit'], unique=False)
    op.create_index('idx_productstoredata_matching_status', 'productstoredata', ['matching_status'], unique=False)
    op.create_index('idx_productstoredata_last_updated', 'productstoredata', ['last_updated'], unique=False)
    op.create_index('idx_productstoredata_additional_attributes', 'productstoredata', ['additional_attributes'], unique=False)
    op.drop_constraint(None, 'products', type_='foreignkey')
    op.create_foreign_key('fk_category', 'products', 'categories', ['category_id'], ['category_id'], onupdate='CASCADE', ondelete='SET NULL')
    op.drop_index(op.f('ix_products_product_id'), table_name='products')
    op.drop_index(op.f('ix_products_name'), table_name='products')
    op.create_index('idx_products_name_trgm', 'products', ['name'], unique=False)
    op.create_index('idx_products_name', 'products', ['name'], unique=False)
    op.create_index('idx_products_category_id', 'products', ['category_id'], unique=False)
    op.drop_index(op.f('ix_productpricehistory_price_history_id'), table_name='productpricehistory')
    op.create_index('idx_pricehistory_recorded_at', 'productpricehistory', ['recorded_at'], unique=False)
    op.create_index('idx_pricehistory_product_store_id', 'productpricehistory', ['product_store_id'], unique=False)
    op.drop_index(op.f('ix_productmatchinglog_log_id'), table_name='productmatchinglog')
    op.create_index('idx_product_matching_log_product_id', 'productmatchinglog', ['product_id'], unique=False)
    op.create_index('idx_product_matching_log_confidence_score', 'productmatchinglog', ['confidence_score'], unique=False)
    op.drop_constraint(None, 'categories', type_='foreignkey')
    op.create_foreign_key('fk_parent_category', 'categories', 'categories', ['parent_id'], ['category_id'], onupdate='CASCADE', ondelete='SET NULL')
    op.drop_index(op.f('ix_categories_category_id'), table_name='categories')
    op.create_unique_constraint('uq_category_name_parent', 'categories', ['name', 'parent_id'])
    op.create_index('idx_categories_parent_id', 'categories', ['parent_id'], unique=False)
    op.create_index('idx_categories_name', 'categories', ['name'], unique=False)
    # ### end Alembic commands ###
